INSERT INTO tb_student(sname, scity) VALUES('RAJENDRA AGARWAL', 'KOLKATA');
INSERT INTO tb_student(sname, scity) VALUES('Pradeep kumar yadav', 'LUCKNOW');
INSERT INTO tb_student(sname, scity) VALUES('mendra mestry', 'MUMBAI');
INSERT INTO tb_student(sname, scity) VALUES('jesmy', 'THALASSERY');
INSERT INTO tb_student(sname, scity) VALUES('Tariq Ahmad', 'ANANTHNAG');
INSERT INTO tb_student(sname, scity) VALUES('Soumitro Banerjee', 'MURSHIDABAD');
INSERT INTO tb_student(sname, scity) VALUES('RAJU', 'BANGALORE');
INSERT INTO tb_student(sname, scity) VALUES('Zamaj Nazeer ahmed', 'SHOLAPUR');
INSERT INTO tb_student(sname, scity) VALUES('radhesham', 'VARANASI');
INSERT INTO tb_student(sname, scity) VALUES('satish hablani', 'RAIPUR');
INSERT INTO tb_student(sname, scity) VALUES('satish hablani', 'RAIPUR');
INSERT INTO tb_student(sname, scity) VALUES('Sms refuls kari', 'BARWANI');
INSERT INTO tb_student(sname, scity) VALUES('Sms refuls kari', 'BARWANI');
INSERT INTO tb_student(sname, scity) VALUES('Brajeah tiwari', 'ADELGAON');
INSERT INTO tb_student(sname, scity) VALUES('Sahzad', 'MUZAFFARNAGAR');
INSERT INTO tb_student(sname, scity) VALUES('Jaspal Singh', 'TARN');
INSERT INTO tb_student(sname, scity) VALUES('Nantu Chandra Laha', 'MURSHIDABAD');
INSERT INTO tb_student(sname, scity) VALUES('Sonu .', 'RAJAURI');
INSERT INTO tb_student(sname, scity) VALUES('santhosh kumar', 'THALASSERY');
INSERT INTO tb_student(sname, scity) VALUES('SUNITA MISHRA', 'LUCKNOW');
INSERT INTO tb_student(sname, scity) VALUES('SUNITA MISHRA', 'LUCKNOW');
INSERT INTO tb_student(sname, scity) VALUES('anil relia', 'DELHI');
INSERT INTO tb_student(sname, scity) VALUES('Umer Khan Enterprises', 'KOTA');
INSERT INTO tb_student(sname, scity) VALUES('DVR.Murthy', 'SRIKAKULAM');
INSERT INTO tb_student(sname, scity) VALUES('atsino', 'DIMAPUR');
INSERT INTO tb_student(sname, scity) VALUES('gangamma', 'MADIKERI');
INSERT INTO tb_student(sname, scity) VALUES('Damru pujari', 'JAIJAIPUR');
INSERT INTO tb_student(sname, scity) VALUES('karan Singh', 'LUDHIANA');
INSERT INTO tb_student(sname, scity) VALUES('Pooja vekariya', 'KARJAT');
INSERT INTO tb_student(sname, scity) VALUES('manjula', 'BHOPAL');
INSERT INTO tb_student(sname, scity) VALUES('Rahul', 'AJMER');
INSERT INTO tb_student(sname, scity) VALUES('abdulla', 'LUCKNOW');
INSERT INTO tb_student(sname, scity) VALUES('khem singh', 'MANDI');
INSERT INTO tb_student(sname, scity) VALUES('Dharmendar kumar', 'PATNA');
INSERT INTO tb_student(sname, scity) VALUES('Satendra pal singh', 'AMBIKAPUR');
INSERT INTO tb_student(sname, scity) VALUES('Amardeep lakra', 'SUNDARGARH');
INSERT INTO tb_student(sname, scity) VALUES('Anil gupta', 'JAMMU');
INSERT INTO tb_student(sname, scity) VALUES('Firoj', 'JHAJJAR');
INSERT INTO tb_student(sname, scity) VALUES('Arun Gupta', 'PANCHKULA');
